Declare argument type when int for float.
Allows setting values via command-line, fixes issues such as:
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [8000] of <class 'str'>
where 8000 was being passed as a string instead of an integer